"""Link layer: Connection (socket + held desires + streaming/telemetry) + exchange
bytes + typed API objects. No separate "session" class — see connection.py
docstring for why streaming/telemetry-publish live on Connection directly."""
from .api_types import (
    IDLE,
    LED_DESIRE_MODES,
    LED_MODE_BLINK_RED_FAST,
    LED_MODE_BLINK_YELLOW_SLOW,
    LED_MODE_FLASH,
    LED_MODE_IDLE_CORNFLOWER,
    LED_MODE_OFF,
    LED_MODE_SOLID_GREEN,
    LED_MODE_SOLID_RED,
    LED_MODE_SOLID_YELLOW,
    LED_MODE_TEST,
    ActuatorDesire,
    CommandImage,
    FeedbackImage,
    FeedbackState,
    LedDesire,
    McuState,
    PlantBlockReason,
    ServoDesire,
)
from .connection import HOST_STALE_MS, Connection
from .exceptions import (
    ControlsHubError,
    FeedbackTimeoutError,
    InvalidFrameError,
    InvalidSlotError,
    NotConnectedError,
)

__all__ = [
    "IDLE",
    "ActuatorDesire",
    "CommandImage",
    "Connection",
    "ControlsHubError",
    "FeedbackImage",
    "FeedbackState",
    "FeedbackTimeoutError",
    "HOST_STALE_MS",
    "InvalidFrameError",
    "InvalidSlotError",
    "LED_DESIRE_MODES",
    "LED_MODE_BLINK_RED_FAST",
    "LED_MODE_BLINK_YELLOW_SLOW",
    "LED_MODE_FLASH",
    "LED_MODE_IDLE_CORNFLOWER",
    "LED_MODE_OFF",
    "LED_MODE_SOLID_GREEN",
    "LED_MODE_SOLID_RED",
    "LED_MODE_SOLID_YELLOW",
    "LED_MODE_TEST",
    "LedDesire",
    "McuState",
    "NotConnectedError",
    "PlantBlockReason",
    "ServoDesire",
]
