"""YAM / deft_vbeta-shaped drivers on HostProxy (via PcbRobotSession).

Product path only — lab uses ``pcb_lab``; wire/DEBUG uses Hub/bench.
See docs/integration.md.
"""
from __future__ import annotations

from deft_controls_sdk.vbeta.arm import (
    PcbArmDriver,
    RobotDeviceAlreadyConnectedError,
    RobotDeviceNotConnectedError,
)
from deft_controls_sdk.vbeta.cfg import (
    ensure_yam_left_arm_cfg,
    ensure_yam_product_cfg,
    pause_plant_stream,
    table_matches_yam,
    table_matches_yam_left,
)
from deft_controls_sdk.vbeta.leds import (
    LED_MODE_BLINK_RED_FAST,
    LED_MODE_BLINK_YELLOW_SLOW,
    LED_MODE_FLASH,
    LED_MODE_IDLE_CORNFLOWER,
    LED_MODE_OFF,
    LED_MODE_SOLID_GREEN,
    LED_MODE_SOLID_RED,
    LED_MODE_SOLID_YELLOW,
    LED_MODE_TEST,
    led_caution,
    led_fault,
    led_flash,
    led_idle,
    led_off,
    led_solid_green,
    led_solid_red,
    led_solid_yellow,
    led_test,
    set_led,
)
from deft_controls_sdk.vbeta.neck import PcbNeckDriver, deg_to_steps, steps_to_deg
from deft_controls_sdk.vbeta.platform import PcbPlatformClient
from deft_controls_sdk.vbeta.rig import (
    RIG_RS02_BUS6_MOTOR_ID,
    RIG_RS02_BUS6_SLOT,
    RigComponents,
    RigTickResult,
    neck_hold_present,
    pdb_poll,
    robstride_soft_hold,
)
from deft_controls_sdk.vbeta.session import PcbRobotSession
from deft_controls_sdk.vbeta.slots import (
    BASE_DRIVE_SLOTS,
    BASE_SLOTS,
    BASE_STEER_SLOTS,
    LEFT_ARM_SLOTS,
    LIFT_SLOT,
    RIGHT_ARM_SLOTS,
    arm_slots,
    yam_left_arm_rows,
    yam_product_rows,
)
from deft_controls_sdk.vbeta.yam_limits import (
    ARM_JOINT_COUNT,
    DEFAULT_CLEAR_INSET,
    DEFAULT_YAM_XML,
    J7_MOTOR_HI,
    J7_MOTOR_LO,
    SOFT_MARGIN,
    JointLimit,
    apply_clear_inset,
    clamp_absolute,
    clamp_delta,
    clamp_q7,
    limits_for_side,
    load_bench_clear_left,
    load_yam_limits,
    plan_hold_q7,
    plan_jog_q7,
    soft_limits_q7,
)

__all__ = [
    "BASE_DRIVE_SLOTS",
    "BASE_SLOTS",
    "BASE_STEER_SLOTS",
    "LEFT_ARM_SLOTS",
    "LIFT_SLOT",
    "LED_MODE_BLINK_RED_FAST",
    "LED_MODE_BLINK_YELLOW_SLOW",
    "LED_MODE_FLASH",
    "LED_MODE_IDLE_CORNFLOWER",
    "LED_MODE_OFF",
    "LED_MODE_SOLID_GREEN",
    "LED_MODE_SOLID_RED",
    "LED_MODE_SOLID_YELLOW",
    "LED_MODE_TEST",
    "PcbArmDriver",
    "PcbNeckDriver",
    "PcbPlatformClient",
    "PcbRobotSession",
    "RIG_RS02_BUS6_MOTOR_ID",
    "RIG_RS02_BUS6_SLOT",
    "RIGHT_ARM_SLOTS",
    "RigComponents",
    "RigTickResult",
    "RobotDeviceAlreadyConnectedError",
    "RobotDeviceNotConnectedError",
    "ARM_JOINT_COUNT",
    "DEFAULT_CLEAR_INSET",
    "DEFAULT_YAM_XML",
    "J7_MOTOR_HI",
    "J7_MOTOR_LO",
    "SOFT_MARGIN",
    "JointLimit",
    "apply_clear_inset",
    "arm_slots",
    "clamp_absolute",
    "clamp_delta",
    "clamp_q7",
    "deg_to_steps",
    "ensure_yam_left_arm_cfg",
    "ensure_yam_product_cfg",
    "pause_plant_stream",
    "led_caution",
    "led_fault",
    "led_flash",
    "led_idle",
    "led_off",
    "led_solid_green",
    "led_solid_red",
    "led_solid_yellow",
    "led_test",
    "limits_for_side",
    "load_bench_clear_left",
    "load_yam_limits",
    "neck_hold_present",
    "pdb_poll",
    "plan_hold_q7",
    "plan_jog_q7",
    "robstride_soft_hold",
    "set_led",
    "soft_limits_q7",
    "steps_to_deg",
    "table_matches_yam",
    "table_matches_yam_left",
    "yam_left_arm_rows",
    "yam_product_rows",
]
