"""YAM product slot map and CFG rows — thin re-exports from ``config``.

Slot constants and row builders live in ``deft_controls_sdk.config``.
"""
from __future__ import annotations

from deft_controls_sdk.config import (
    BASE_DRIVE_SLOTS,
    BASE_SLOTS,
    BASE_STEER_SLOTS,
    DEFAULT_ARM_KD,
    DEFAULT_ARM_KP,
    DEFAULT_DRIVE_KD,
    DEFAULT_STEER_KD,
    DEFAULT_STEER_KP,
    LEFT_ARM_SLOTS,
    LIFT_SLOT,
    NECK_PITCH_DXL_ID,
    NECK_PITCH_SERVO_SLOT,
    NECK_YAW_DXL_ID,
    NECK_YAW_SERVO_SLOT,
    PROTO_CUBEMARS,
    PROTO_DAMIAO,
    PROTO_NONE,
    PROTO_ROBSTRIDE,
    PROTO_ZEROERR,
    RIGHT_ARM_SLOTS,
    SERVO_MODEL_NAMES,
    SERVO_MODEL_XL330_M288,
    SERVO_MODEL_XL430,
    SPARE_SLOTS,
    arm_slots,
    cubemars_yam_rows,
    slots_by_bus,
    yam_left_arm_rows,
    yam_product_rows,
)
from deft_controls_sdk.config.actuator import DAMIAO_MASTER_IDS, _DAMIAO_MASTER

__all__ = [
    "BASE_DRIVE_SLOTS",
    "BASE_SLOTS",
    "BASE_STEER_SLOTS",
    "DEFAULT_ARM_KD",
    "DEFAULT_ARM_KP",
    "DEFAULT_DRIVE_KD",
    "DEFAULT_STEER_KD",
    "DEFAULT_STEER_KP",
    "LEFT_ARM_SLOTS",
    "LIFT_SLOT",
    "NECK_PITCH_DXL_ID",
    "NECK_PITCH_SERVO_SLOT",
    "NECK_YAW_DXL_ID",
    "NECK_YAW_SERVO_SLOT",
    "PROTO_CUBEMARS",
    "PROTO_DAMIAO",
    "PROTO_NONE",
    "PROTO_ROBSTRIDE",
    "PROTO_ZEROERR",
    "RIGHT_ARM_SLOTS",
    "SERVO_MODEL_NAMES",
    "SERVO_MODEL_XL330_M288",
    "SERVO_MODEL_XL430",
    "SPARE_SLOTS",
    "arm_slots",
    "cubemars_yam_rows",
    "slots_by_bus",
    "yam_left_arm_rows",
    "yam_product_rows",
]
