"""Controls <-> PDB (Power Distribution Board) UART link — 64 B frames.

  frame.py   — pack/parse/CRC16 for PDBC (command) / PDBF (feedback)
  framing.py — byte-stream framer (resync on corrupt frames)

Wire contract: docs/pdb-uart-v1.md. Separate physical link (UART4) from the
USB host_exchange image in deft_controls_sdk.link.exchange.
"""
from __future__ import annotations

from .frame import (
    CMD_OFF_HEARTBEAT,
    CMD_OFF_KILL_REQ,
    CMD_OFF_RAIL_ENABLE,
    FB_OFF_CONTACTOR,
    FB_OFF_ESTOP_SENSE,
    FB_OFF_FAULT_FLAGS,
    FB_OFF_HB_ECHO,
    FB_OFF_KILL_REASON,
    FB_OFF_KILL_STATE,
    FB_OFF_PACK_I,
    FB_OFF_PACK_V,
    FB_OFF_RAIL_I,
    FB_OFF_RAIL_V,
    FRAME_BYTES,
    KILL_HARD_ESTOP,
    KILL_NORMAL,
    KILL_REASON_BUTTON,
    KILL_REASON_COMMS_LOSS,
    KILL_REASON_HOST,
    KILL_REASON_NAMES,
    KILL_REASON_NONE,
    KILL_REASON_OTHER,
    KILL_REASON_OVERCURRENT,
    KILL_REASON_OVERTEMP,
    KILL_REASON_UNDERVOLTAGE,
    KILL_SOFT_READY,
    KILL_SOFT_REQ,
    KILL_STATE_NAMES,
    MAGIC_CMD,
    MAGIC_FB,
    OFF_CRC,
    OFF_FLAGS,
    OFF_MAGIC,
    OFF_PAYLOAD,
    OFF_SEQ,
    OFF_VERSION,
    STALE_MS,
    TX_PERIOD_MS,
    VERSION,
    crc16,
    is_frame_valid,
    pack_command,
    pack_feedback,
    parse_command,
    parse_feedback,
)
from .framing import PdbFrameReader

__all__ = [
    "CMD_OFF_HEARTBEAT",
    "CMD_OFF_KILL_REQ",
    "CMD_OFF_RAIL_ENABLE",
    "FB_OFF_CONTACTOR",
    "FB_OFF_ESTOP_SENSE",
    "FB_OFF_FAULT_FLAGS",
    "FB_OFF_HB_ECHO",
    "FB_OFF_KILL_REASON",
    "FB_OFF_KILL_STATE",
    "FB_OFF_PACK_I",
    "FB_OFF_PACK_V",
    "FB_OFF_RAIL_I",
    "FB_OFF_RAIL_V",
    "FRAME_BYTES",
    "KILL_HARD_ESTOP",
    "KILL_NORMAL",
    "KILL_REASON_BUTTON",
    "KILL_REASON_COMMS_LOSS",
    "KILL_REASON_HOST",
    "KILL_REASON_NAMES",
    "KILL_REASON_NONE",
    "KILL_REASON_OTHER",
    "KILL_REASON_OVERCURRENT",
    "KILL_REASON_OVERTEMP",
    "KILL_REASON_UNDERVOLTAGE",
    "KILL_SOFT_READY",
    "KILL_SOFT_REQ",
    "KILL_STATE_NAMES",
    "MAGIC_CMD",
    "MAGIC_FB",
    "OFF_CRC",
    "OFF_FLAGS",
    "OFF_MAGIC",
    "OFF_PAYLOAD",
    "OFF_SEQ",
    "OFF_VERSION",
    "PdbFrameReader",
    "STALE_MS",
    "TX_PERIOD_MS",
    "VERSION",
    "crc16",
    "is_frame_valid",
    "pack_command",
    "pack_feedback",
    "parse_command",
    "parse_feedback",
]
