"""config — assemblies / typed profiles / CFG row builders (controls substrate).

Identity layers (peripheral-homogeneous)::

    ActuatorProfile / ServoProfile  — one family only
    Assembly                        — composition + overlap checks for HostProxy
    Profile                         — actuator demux shim for HostProxy

Assemblies are SDK config for controls — not pcb_lab-owned identity.
Not plant command TX (see ``actions``) and not DEBUG wire RPC (see ``debug.config``).
"""
from __future__ import annotations

from .actuator import (
    ActuatorGains,
    ActuatorKind,
    COMPONENT_ACTUATOR_KIND,
    DEFAULT_ARM_KD,
    DEFAULT_ARM_KP,
    DEFAULT_DRIVE_KD,
    DEFAULT_HOLD_KD,
    DEFAULT_HOLD_KP,
    DEFAULT_HOLD_TORQUE,
    DEFAULT_JOINT_KD,
    DEFAULT_JOINT_KP,
    DEFAULT_JOINT_TORQUE,
    DEFAULT_STEER_KD,
    DEFAULT_STEER_KP,
    DEFAULT_WHEEL_KD,
    DEFAULT_WHEEL_KP,
    DEFAULT_WHEEL_TORQUE,
    JOINT_GAINS,
    PROTO_CUBEMARS,
    PROTO_DAMIAO,
    PROTO_NONE,
    PROTO_ROBSTRIDE,
    PROTO_ZEROERR,
    WHEEL_GAINS,
    arm_slots,
    cubemars_yam_rows,
    gains_for_kind,
    kind_for_component,
    resolve_gain_vectors,
    resolve_hold_gains,
    slots_by_bus,
    yam_left_arm_rows,
    yam_product_rows,
)
from .assembly import (
    Assembly,
    assembly_from_name,
    assembly_put_actuator,
    assembly_put_servo,
    assembly_remove_actuator,
    bench_continuous_assembly,
    yam_product_assembly,
)
from .firmware import default_firmware_elf
from .led import LED_PRESETS, LedPreset
from .pdu_link import DEFAULT_BENCH_LISTEN_PDU, DEFAULT_PRODUCT_LISTEN_PDU
from .profile import (
    BASE_DRIVE_SLOTS,
    BASE_SLOTS,
    BASE_STEER_SLOTS,
    BASE_WHEEL_1_SLOTS,
    BASE_WHEEL_2_SLOTS,
    BASE_WHEEL_3_SLOTS,
    BASE_WHEEL_SLOTS,
    BENCH_BASE_SLOTS,
    LEFT_ARM_SLOTS,
    LIFT_SLOT,
    NECK_PITCH_SERVO_SLOT,
    NECK_YAW_SERVO_SLOT,
    PRODUCT_ACTUATOR_SECTIONS,
    Profile,
    RIGHT_ARM_SLOTS,
    SPARE_SLOTS,
    TORSO_SLOT,
    bench_continuous_profile,
    yam_product_profile,
)
from .servo import (
    NECK_PITCH_DXL_ID,
    NECK_YAW_DXL_ID,
    SERVO_MODEL_NAMES,
    SERVO_MODEL_XL330_M288,
    SERVO_MODEL_XL430,
)
from .product_cfg import (
    ensure_yam_left_arm_cfg,
    ensure_yam_product_cfg,
    table_matches_yam,
    table_matches_yam_left,
)
from .typed_profiles import (
    ActuatorProfile,
    CfgSlotSpec,
    ServoEntry,
    ServoProfile,
    arm_profile,
    base_wheel_profile,
    cfg_specs_from_table,
    cfg_specs_from_yam_slots,
    lift_profile,
    neck_profile,
    parse_protocol,
    parse_slots_spec,
    single_profile,
    torso_profile,
    wheel_profile,
)
from . import yam_bench_clear_left
from .yam_limits import (
    ARM_JOINT_COUNT,
    SOFT_MARGIN,
    apply_clear_inset,
    clamp_absolute,
    clamp_delta,
    clamp_q7,
    limits_for_side,
    load_yam_limits,
    plan_hold_q7,
    plan_jog_q7,
    soft_limits_q7,
)

__all__ = [
    "ActuatorGains",
    "ActuatorKind",
    "ActuatorProfile",
    "Assembly",
    "BASE_DRIVE_SLOTS",
    "BASE_SLOTS",
    "BASE_STEER_SLOTS",
    "BASE_WHEEL_1_SLOTS",
    "BASE_WHEEL_2_SLOTS",
    "BASE_WHEEL_3_SLOTS",
    "BASE_WHEEL_SLOTS",
    "BENCH_BASE_SLOTS",
    "COMPONENT_ACTUATOR_KIND",
    "CfgSlotSpec",
    "DEFAULT_ARM_KD",
    "DEFAULT_ARM_KP",
    "DEFAULT_BENCH_LISTEN_PDU",
    "DEFAULT_DRIVE_KD",
    "DEFAULT_HOLD_KD",
    "DEFAULT_HOLD_KP",
    "DEFAULT_HOLD_TORQUE",
    "DEFAULT_JOINT_KD",
    "DEFAULT_JOINT_KP",
    "DEFAULT_JOINT_TORQUE",
    "DEFAULT_PRODUCT_LISTEN_PDU",
    "DEFAULT_STEER_KD",
    "DEFAULT_STEER_KP",
    "DEFAULT_WHEEL_KD",
    "DEFAULT_WHEEL_KP",
    "DEFAULT_WHEEL_TORQUE",
    "JOINT_GAINS",
    "LEFT_ARM_SLOTS",
    "LED_PRESETS",
    "LIFT_SLOT",
    "LedPreset",
    "NECK_PITCH_DXL_ID",
    "NECK_PITCH_SERVO_SLOT",
    "NECK_YAW_DXL_ID",
    "NECK_YAW_SERVO_SLOT",
    "PRODUCT_ACTUATOR_SECTIONS",
    "PROTO_CUBEMARS",
    "PROTO_DAMIAO",
    "PROTO_NONE",
    "PROTO_ROBSTRIDE",
    "PROTO_ZEROERR",
    "Profile",
    "RIGHT_ARM_SLOTS",
    "SERVO_MODEL_NAMES",
    "SERVO_MODEL_XL330_M288",
    "SERVO_MODEL_XL430",
    "SPARE_SLOTS",
    "ServoEntry",
    "ServoProfile",
    "TORSO_SLOT",
    "WHEEL_GAINS",
    "arm_profile",
    "arm_slots",
    "assembly_from_name",
    "assembly_put_actuator",
    "assembly_put_servo",
    "assembly_remove_actuator",
    "base_wheel_profile",
    "bench_continuous_assembly",
    "bench_continuous_profile",
    "cfg_specs_from_table",
    "cfg_specs_from_yam_slots",
    "cubemars_yam_rows",
    "default_firmware_elf",
    "ensure_yam_left_arm_cfg",
    "ensure_yam_product_cfg",
    "gains_for_kind",
    "kind_for_component",
    "lift_profile",
    "neck_profile",
    "parse_protocol",
    "parse_slots_spec",
    "resolve_gain_vectors",
    "resolve_hold_gains",
    "single_profile",
    "slots_by_bus",
    "table_matches_yam",
    "table_matches_yam_left",
    "torso_profile",
    "wheel_profile",
    "yam_bench_clear_left",
    "yam_left_arm_rows",
    "yam_product_assembly",
    "yam_product_profile",
    "yam_product_rows",
    "ARM_JOINT_COUNT",
    "SOFT_MARGIN",
    "apply_clear_inset",
    "clamp_absolute",
    "clamp_delta",
    "clamp_q7",
    "limits_for_side",
    "load_yam_limits",
    "plan_hold_q7",
    "plan_jog_q7",
    "soft_limits_q7",
]
