"""
Host exchange layout — mirrors App/Inc/host/host_exchange_schema.h and plant_command.h.
Layout v2 (672 B). Prefer scripts/deft_controls_sdk for new work.
"""
from __future__ import annotations

HOST_COMMAND_MAGIC = 0x434D4448
HOST_FEEDBACK_MAGIC = 0x46424848
HOST_LAYOUT_VERSION = 2
IMAGE_BYTES = 672

HOST_EXCHANGE_ACTUATOR_SLOTS = 25
HOST_EXCHANGE_SERVO_SLOTS = 2
HOST_EXCHANGE_LED_SLOTS = 1
HOST_PDU_PAYLOAD_BYTES = 32
HOST_PDB_PAYLOAD_BYTES = 64

ACTUATOR_COUNT = 14  # dual YAM: slots 0-6 arm1 (CH1), 7-13 arm2 (CH2)

# CFG GET reply is paginated when ACTUATOR_COUNT exceeds one PDU's worth of slots —
# mirrors PLANT_CFG_GET_SLOTS_PER_PAGE in App/Src/plant/plant_config_nvm.c.
CFG_GET_SLOTS_PER_PAGE = (HOST_PDU_PAYLOAD_BYTES - 6 - 2) // 3

# Byte offsets in the 672 B command/feedback image (layout v2).
HEADER_OFF = 0
SYSTEM_CMD_OFF = 12
SYSTEM_BYTES = 32
ACTUATOR0_OFF = 44
ACTUATOR_SLOT_BYTES = 22
SERVO_SLOT_BYTES = 6
SERVO0_CMD_OFF = ACTUATOR0_OFF + HOST_EXCHANGE_ACTUATOR_SLOTS * ACTUATOR_SLOT_BYTES
SERVO0_FB_OFF = SERVO0_CMD_OFF
LED_CMD_OFF = SERVO0_CMD_OFF + HOST_EXCHANGE_SERVO_SLOTS * SERVO_SLOT_BYTES
PDB_OFF = LED_CMD_OFF + 2
PDU_OFF = PDB_OFF  # DEBUG mailbox = pdb[0..31]
PDU_BUS_OFF = PDU_OFF + 11

PLANT_MCU_STATE_NORMAL = 0
PLANT_MCU_STATE_RECOVERY = 1
PLANT_MCU_STATE_DIAG_ONLY = 2
PLANT_MCU_STATE_ESTOP = 3

MIN_CAN_BUS = 1
MAX_CAN_BUS = 6

DEFAULT_BAUD = 115200
STM32_VID = 0x0483
STM32_USB_CDC_PID = 0x5740
STM32_STLINK_VCP_PID = 0x3754
