"""Byte contract helpers for the 562 B host exchange image.

  wire_layout.py — constants / offsets (plant path; renamed from schema.py —
                   "schema" already means something else in telemetry/cache.py)
  transport.py   — serial open + frame reader
  pack.py        — build/patch command image bytes (plant path, pdu=0)
  parse.py       — parse feedback image bytes (plant path)
  bench.py       — tagged-pdu (DEBUG mode) pack/parse: RS2/DM0/CFG + CAN bus helpers
"""
from __future__ import annotations

from .bench import (
    CFG_OP_GET,
    CFG_OP_SAVE,
    CFG_OP_SET,
    CFG_RESP_TAG0,
    CFG_RESP_TAG1,
    CFG_RESP_TAG2,
    CFG_STATUS_NAMES,
    CFG_STATUS_OK,
    DM_MASTER_ANY,
    DM_PROBE_ID_SWEEP,
    DM_PROBE_KIND_NAMES,
    DM_PROBE_REG_SCAN,
    DM_REG_ESC_ID,
    DM_RESP_TAG,
    MCP_CAN_BUSES,
    PROBE_ENABLE_ONLY,
    PROBE_PROMISC,
    PROBE_RESET,
    RS2_RESP_TAG,
    SESSION_BEGIN,
    SESSION_END,
    build_cfg_command,
    build_dm_probe_command,
    build_rs2_probe_command,
    build_rs2_scan_command,
    can_bus_label,
    dm_fault_found,
    is_mcp_bus,
    normalize_can_bus,
    parse_cfg_feedback,
    parse_dm_from_actuator,
    parse_dm_probe_pdu,
    parse_probe_pdu,
    probe_kind_matches,
)
from .pack import (
    actuator_slot_offset,
    build_actuator_command,
    build_plant_command,
    patch_actuator_desire,
    patch_system_mcu_state,
)
from .parse import (
    PLANT_BLOCK_NAMES,
    parse_actuator_feedback,
    parse_feedback_header,
    parse_svd_plant_timing,
    parse_thermo_led_debug,
)
from .transport import (
    FrameReader,
    SerialRxPump,
    auto_pick_port,
    describe_open_port,
    list_ports_info,
    open_serial,
)
from .wire_layout import (
    ACTUATOR_COUNT,
    DEFAULT_BAUD,
    HOST_COMMAND_MAGIC,
    HOST_EXCHANGE_ACTUATOR_SLOTS,
    HOST_FEEDBACK_MAGIC,
    HOST_LAYOUT_VERSION,
    IMAGE_BYTES,
    PDU_OFF,
    PLANT_MCU_STATE_DIAG_ONLY,
    PLANT_MCU_STATE_ESTOP,
    PLANT_MCU_STATE_NORMAL,
    PLANT_MCU_STATE_RECOVERY,
)

__all__ = [
    "ACTUATOR_COUNT",
    "CFG_OP_GET",
    "CFG_OP_SAVE",
    "CFG_OP_SET",
    "CFG_RESP_TAG0",
    "CFG_RESP_TAG1",
    "CFG_RESP_TAG2",
    "CFG_STATUS_NAMES",
    "CFG_STATUS_OK",
    "DEFAULT_BAUD",
    "DM_MASTER_ANY",
    "DM_PROBE_ID_SWEEP",
    "DM_PROBE_KIND_NAMES",
    "DM_PROBE_REG_SCAN",
    "DM_REG_ESC_ID",
    "DM_RESP_TAG",
    "HOST_COMMAND_MAGIC",
    "HOST_EXCHANGE_ACTUATOR_SLOTS",
    "HOST_FEEDBACK_MAGIC",
    "HOST_LAYOUT_VERSION",
    "IMAGE_BYTES",
    "MCP_CAN_BUSES",
    "PDU_OFF",
    "PLANT_BLOCK_NAMES",
    "PLANT_MCU_STATE_DIAG_ONLY",
    "PLANT_MCU_STATE_ESTOP",
    "PLANT_MCU_STATE_NORMAL",
    "PLANT_MCU_STATE_RECOVERY",
    "PROBE_ENABLE_ONLY",
    "PROBE_PROMISC",
    "PROBE_RESET",
    "RS2_RESP_TAG",
    "SESSION_BEGIN",
    "SESSION_END",
    "FrameReader",
    "SerialRxPump",
    "actuator_slot_offset",
    "auto_pick_port",
    "build_actuator_command",
    "build_cfg_command",
    "build_dm_probe_command",
    "build_plant_command",
    "build_rs2_probe_command",
    "build_rs2_scan_command",
    "can_bus_label",
    "describe_open_port",
    "dm_fault_found",
    "is_mcp_bus",
    "list_ports_info",
    "normalize_can_bus",
    "open_serial",
    "parse_actuator_feedback",
    "parse_cfg_feedback",
    "parse_dm_from_actuator",
    "parse_dm_probe_pdu",
    "parse_feedback_header",
    "parse_probe_pdu",
    "parse_svd_plant_timing",
    "parse_thermo_led_debug",
    "patch_actuator_desire",
    "patch_system_mcu_state",
    "probe_kind_matches",
]
