"""Host exchange layout v3 — mirrors App/Inc/host/host_exchange_schema.h."""
from __future__ import annotations

HOST_COMMAND_MAGIC = 0x434D4448  # CMDH plant
HOST_FEEDBACK_MAGIC = 0x46424848  # HBHF plant
HOST_DEBUG_COMMAND_MAGIC = 0x44424743  # DBGC
HOST_DEBUG_FEEDBACK_MAGIC = 0x46424744  # DBGF
HOST_LAYOUT_VERSION = 3
IMAGE_BYTES = 694
DEBUG_MAILBOX_OFF = 630  # pdb[0..31]; same offset as plant PDB_OFF

HOST_EXCHANGE_ACTUATOR_SLOTS = 26
HOST_EXCHANGE_SERVO_SLOTS = 2
HOST_EXCHANGE_LED_SLOTS = 1
HOST_PDU_PAYLOAD_BYTES = 32  # DEBUG mailbox = pdb[0..31]
HOST_PDB_PAYLOAD_BYTES = 64

ACTUATOR_COUNT = HOST_EXCHANGE_ACTUATOR_SLOTS  # plant table == wire slots (26)

HEADER_OFF = 0
SYSTEM_CMD_OFF = 12
SYSTEM_FB_OFF = 12
SYSTEM_BYTES = 32
ACTUATOR0_OFF = 44  # after 12 B header + 32 B system
ACTUATOR_SLOT_BYTES = 22  # 20 B MIT + 2 B meta
SERVO_SLOT_BYTES = 6
SERVO0_CMD_OFF = ACTUATOR0_OFF + HOST_EXCHANGE_ACTUATOR_SLOTS * ACTUATOR_SLOT_BYTES
SERVO0_FB_OFF = SERVO0_CMD_OFF  # 616
LED_CMD_OFF = SERVO0_CMD_OFF + HOST_EXCHANGE_SERVO_SLOTS * SERVO_SLOT_BYTES  # 628
PDB_OFF = LED_CMD_OFF + 2  # 630
PDU_OFF = PDB_OFF  # DEBUG mailbox alias
PDU_BUS_OFF = PDU_OFF + 11

PLANT_MCU_STATE_NORMAL = 0
PLANT_MCU_STATE_RECOVERY = 1
PLANT_MCU_STATE_DIAG_ONLY = 2  # deprecated host alias; FW forces plant_apply=0
PLANT_MCU_STATE_ESTOP = 3

DEFAULT_BAUD = 115200
STM32_VID = 0x0483
STM32_USB_CDC_PID = 0x5740
STM32_STLINK_VCP_PID = 0x3754

MIN_CAN_BUS = 1
MAX_CAN_BUS = 6

# Link mode (ADR-004) — system.reserved bits4..5 / wire bits9..10
STM32_MODE_BANDWIDTH = 0  # plant CMDH/HBHF only; no debug lanes
STM32_MODE_DEBUG = 1
STM32_MODE_SOFT_DFU = 2
STM32_MODE_SHIFT = 9  # absolute wire bit position in system u32
STM32_MODE_MASK = 0x3
STM32_MODE_NAMES = {
    STM32_MODE_BANDWIDTH: "bandwidth",
    STM32_MODE_DEBUG: "debug",
    STM32_MODE_SOFT_DFU: "soft_dfu",
}

# Plant apply arm — system.reserved bit6 / wire bit11 (observe vs control)
PLANT_APPLY_SHIFT = 11  # absolute wire bit in system u32
PLANT_APPLY_MASK = 0x1

# Debug lanes (DBGC/DBGF) — docs/host-contract.md
DEBUG_LANES_TAG0 = ord("D")
DEBUG_LANES_TAG1 = ord("L")
DEBUG_LANES_VER = 1
DEBUG_LANES_HDR_OFF = 12
DEBUG_LANES_HDR_BYTES = 6
DEBUG_LANE0_OFF = 18
DEBUG_LANE_BYTES = 32
DEBUG_LANE_COUNT = 10
DEBUG_LANE_RS = 0
DEBUG_LANE_CM = 1
DEBUG_LANE_ZE = 2
DEBUG_LANE_DM = 3
DEBUG_LANE_LED = 4
DEBUG_LANE_SERVO = 5
DEBUG_LANE_PDU = 6
DEBUG_LANE_CFG = 7
DEBUG_LANE_R8 = 8
DEBUG_LANE_R9 = 9

# connect(mode=) aliases → stm32_mode
LINK_MODE_ALIASES = {
    "bandwidth": STM32_MODE_BANDWIDTH,
    "debug": STM32_MODE_DEBUG,
    "soft_dfu": STM32_MODE_SOFT_DFU,
}
