"""Host exchange layout v2 — mirrors App/Inc/host/host_exchange_schema.h."""
from __future__ import annotations

HOST_COMMAND_MAGIC = 0x434D4448
HOST_FEEDBACK_MAGIC = 0x46424848
HOST_LAYOUT_VERSION = 2
IMAGE_BYTES = 672

HOST_EXCHANGE_ACTUATOR_SLOTS = 25
HOST_EXCHANGE_SERVO_SLOTS = 2
HOST_EXCHANGE_LED_SLOTS = 1
HOST_PDU_PAYLOAD_BYTES = 32  # DEBUG mailbox = pdb[0..31]
HOST_PDB_PAYLOAD_BYTES = 64

ACTUATOR_COUNT = HOST_EXCHANGE_ACTUATOR_SLOTS  # plant table == wire slots (25)

HEADER_OFF = 0
SYSTEM_CMD_OFF = 12
SYSTEM_FB_OFF = 12
SYSTEM_BYTES = 32
ACTUATOR0_OFF = 44  # after 12 B header + 32 B system
ACTUATOR_SLOT_BYTES = 22  # 20 B MIT + 2 B meta
SERVO_SLOT_BYTES = 6
SERVO0_CMD_OFF = ACTUATOR0_OFF + HOST_EXCHANGE_ACTUATOR_SLOTS * ACTUATOR_SLOT_BYTES
SERVO0_FB_OFF = SERVO0_CMD_OFF  # 594
LED_CMD_OFF = SERVO0_CMD_OFF + HOST_EXCHANGE_SERVO_SLOTS * SERVO_SLOT_BYTES  # 606
PDB_OFF = LED_CMD_OFF + 2  # 608
PDU_OFF = PDB_OFF  # DEBUG mailbox alias
PDU_BUS_OFF = PDU_OFF + 11

PLANT_MCU_STATE_NORMAL = 0
PLANT_MCU_STATE_RECOVERY = 1
PLANT_MCU_STATE_DIAG_ONLY = 2
PLANT_MCU_STATE_ESTOP = 3

DEFAULT_BAUD = 115200
STM32_VID = 0x0483
STM32_USB_CDC_PID = 0x5740
STM32_STLINK_VCP_PID = 0x3754

MIN_CAN_BUS = 1
MAX_CAN_BUS = 6
